### ISSUE TITLE
Cannot find module 'ember-changeset-validations/validators'

### ISSUE THREAD

**Issue by joshfarrant** [poteto/ember-changeset-validations#114]
## Version
1.2.4
## Test Case

```js
// test.js

import { validatePresence } from 'ember-changeset-validations/validators';
console.log(validatePresence);
```
## Steps to reproduce
```
npm install ember-changeset-validations
node test.js
```

## Expected Behavior
I'd expect to see the `validatePresence` function declaration outputted in the logs.

## Actual Behavior
The module cannot be found:
```
Cannot find module 'ember-changeset-validations/validators'
```

Not sure if I'm missing something obvious here, but I tested this within an Ember app and had the same result. Wasn't sure if the problem was with my build process or something, so I thought I'd try the same thing in a single file (as above) and got the same result.

Tested with node 6.9.1

**Comment by jdhines** [comment]
Same issue for me. I'm on Ember 1.12.

**Comment by Kuzirashi** [comment]
I'm on Ember 1.13. Same problem.

**Comment by kevlarr** [comment]
Same issue with 1.13, but using `ember-changeset-validations/validators/index` works here as well.. Good catch, @Kuzirashi

**Comment by snewcomer** [comment]
This may have been an Ember specific issue but not a problem anymore!
