### ISSUE TITLE
How to observe model/changeset properties?

### ISSUE THREAD

**Issue by DavorPadovan** [poteto/ember-changeset-validations#143]
I've added ember-changeset-validations to my Ember app today. I have some computed properties which observe model. They don't work anymore. What am I missing? How can I observe changeset properties?

**Comment by MatthewPringle** [comment]
buttons: Ember.computed( 'changeset.change.' + this.name , function() {

where I'm passing name into the component which is the name of the property in the model


{{questions/question-text
        label     = "Text Question"
        changeset = changeset
        name      = "debugText"
 }}

always remember to pass  changeset = changes like you would do with model = model

**Comment by sbatson5** [comment]
Hi @DavorPadovan, do you have an example? Changesets are designed to not mutate your original model until it is validated or persisted.  So, it may be that your model just isn't being updated in the way you think.  An example with a twiddle or repo would be great!

**Comment by DavorPadovan** [comment]
Yes, my model is not updated. But is there a way to observe changeset?
http://emberjs.jsbin.com/gist/7a36224c990219f48d7432e16c88fb57?html,js,output - this is an example from our app, without changeset validations. Is there a way to change `usdValueObserver` to fire when value in input changes? I know that I can achieve similar thing with actions on inputs, but this will complicate everything...

**Comment by snewcomer** [comment]
Late to the game but we have a test for listening to events via `addObserver` (you) && `notifyPropertyChange` (us)

https://github.com/poteto/ember-changeset/blob/d245d0e1e586a3a1e70fb9d600f34e68a979bef3/tests/unit/changeset-test.js#L1204

**Comment by snewcomer** [comment]
Given `tracked` is a fundamentally different paradigm (pull), we are moving away from `push` based reactivity models
