### ISSUE TITLE
validateFormat regex won't allow blank values

### ISSUE THREAD

**Issue by jeffstagedoor** [poteto/ember-changeset-validations#174]
## Version
1.2.10

## Test Case
```
// validations/text.js
import {
	validateLength,
	validateFormat,
} from 'ember-changeset-validations/validators';

export default {
  text: {
    validateFormat({regex: /^[a-z]*$/ }),
    validateLength({max: 250, allowBlank: true})
  }
};
```

## Steps to reproduce
type something, delete everything, will be `isInvalid=true` and trigger the validateFormat-error 

## Expected Behavior
expecting to be valid, because 1st regex demands zero or more (`*`) and 2nd `allowBlank` is set.

a normal js match would indeed find a blank string:
```
var str = '';
var re = /^[a-z]*$/;
var found = str.match(re);
console.log(found);
// output: ["", index: 0, input: ""]
```

## Actual Behavior
isInvalid
(removing the string-boundaries  `^` and `$` doesn't change anything but of course make the regex obsolete)

**Comment by nucleartide** [comment]
Thanks for opening the issue. I'm kinda short on time right now, but do you encounter the same error on `ember-changeset-validations` 1.2.8?

**Comment by jeffstagedoor** [comment]
I've changed to 1.2.8 and unfortunately the result is the same

**Comment by jeffstagedoor** [comment]
MY FAULT:
adding `allowBlank: true` to `validateFormat` is working.
So 
```
 validateFormat({type: 'email', allowBlank: true}); // all good
```
but 
```
    validateFormat({type: 'email'}),
    validateLength({allowblank: true})
   // not good
```

Sorry for taking your time, I didn't use it correctly. But maybe a hint in the docs would be nice.
