### ISSUE TITLE
Feature Request: validatePresenceOn

### ISSUE THREAD

**Issue by jhitchins88** [poteto/ember-changeset-validations#189]
# Suggested Addition

The `validatePresenceOn` validator: validate presence if other field(s) are also there.

# How it works

```
export default {
  lastName: validatePresenceOn('firstName'),
  password: validatePresenceOn([ 'email', 'ssn', 'address', ])
}
```

Alternatively, it could be an option for the `validatePresence` validator:

```
export default {
  lastName: validatePresence({ on: 'firstName' }),
  password: validatePresence({ on: [ 'email', 'ssn', 'address', ] })
}
```

This is something I wrote as a custom validator, so if it's something you would like, I can put up a PR.

**Comment by snewcomer** [comment]
@jhitchins88 This seems like a phenomenal idea.  Lmk if you have time for a PR!

**Comment by nickschot** [comment]
@jhitchins88 how did you write this validator? Don't the validators only receive the key and the value of the property that is validated?

I'm very interested in this (and a similar validator where at least one of several fields must be present/have a specific format).

**Comment by jhitchins88** [comment]
@snewcomer I should be able to do it.  I'll work it up into a PR soon.

@nickschot I used the `changes` and `content` (4th and 5th parameters)  passed into the validator function.  Those let you look at the whole changeset.

**Comment by musaffa** [comment]
> @nickschot a similar validator where at least one of several fields must be present/have a specific format

@jhitchins88 Can you add this feature as well?

**Comment by jhitchins88** [comment]
@musaffa 

I'd need a little more description of "have a specific format", but I'd be down if we know what that looks like.  If it gets too much  more complicated, we should probably break this functionality into its own validator, or have some way to do conditionals in the `validations` file, like #116 suggests.  This `on` option is basically just a fancy, specific conditional, that could be replaced with a general conditional for any validator in the future.

**Comment by musaffa** [comment]
@nickschot Can you please clarify this format validation of one field in another field?
