### ISSUE TITLE
Support for class based validators 

### ISSUE THREAD

**Issue by bobisjan** [poteto/ember-changeset-validations#197]
Hello 👋,

I have question about using class based validators.

The use case is about having validator dependent on a service.

```javascript
import Validator from 'ember-changeset-validations/validator';
import  { inject as service } from '@ember/service';

export default class PersonalNoValidator extends Validator {
  @service ajax;

  async validate(key, newValue, oldValue, changes, content) {
    try {
      await this.ajax.post('/api/personal-no/validation', { data: newValue });
      return true;
    } catch (_) {
      return 'Personal No is invalid';
    }
  }
}
```

Would it make sense to support this, or is there a path to solve this currently?

Thanks

**Comment by snewcomer** [comment]
@bobisjan Great idea.  I'm working on getting a few things updated.  But we should tackle after that.

**Comment by lindyhopchris** [comment]
This would be a great addition - and I believe would close #124 as that's effectively asking about injecting the store.

**Comment by snewcomer** [comment]
Let's tackle after v3 for ember-changeset && major version bump this package to be compatible!

https://github.com/poteto/ember-changeset/pull/379

**Comment by basz** [comment]
Know that you can do this already if you need to

```
// app/instance-initializers/container.js
import application from 'utils/application';

export function initialize(appInstance) {
  application.instance = appInstance;
}

export default {
  initialize
};
```

```
// app/utils/application.js

export default {
  instance: null
};
```
```
// your/validator.js
import application from 'lab-plhw/utils/application';

const myService = application.instance.lookup('service:myService');
```

**Comment by nickschot** [comment]
What about class based Validations? Would be useful in cases where i.e. a translated `description` needs to be provided.

**Comment by snewcomer** [comment]
> Would it make sense to support this, or is there a path to solve this currently?

Lets see if we can get something working this week 👍
