### ISSUE TITLE
remove `^` from ember-changeset version

### ISSUE THREAD

**Issue by Leooo** [poteto/ember-changeset-validations#201]
We are using both `ember-changeset` and `ember-changeset-validation` packages in our common internal addon (maybe we should only consume `ember-changeset-validation` but the problem would be the same, see below).

Because `ember-changeset-validation` is always using the latest version of `ember-changeset`, this prevents us from being stable when a new `ember-changeset` release is made, even when locking the version of ember-changeset-validation.

Sorry I cannot go into much more details / explanations as we are having master tests failing due to to this and we are forking `ember-changeset-validations` atm to lock the versions as a short term fix, but can I ask if this would be possible to fix the `ember-changeset` package version of this addon instead? Happy to send a PR if approved thanks

**Comment by snewcomer** [comment]
@Leooo Uh oh.  Do you happen to know what exactly is failing so we can fix?  The goal of #198 was to make whatever in this helper 1-1 with what is now in the `ember-changeset` helper.

Also, is it possible to for you to pin `ember-changeset` to 2.2.1 in your package.json file?  But more importantly, I'd be curious as to your use case and what is failing 👍

**Comment by Leooo** [comment]
@snewcomer I'm sure of nothing and have no time to get a the bottom of it right now, but I would guess that the problem is that you having ember-changeset with a `^` in your dependencies forces us to upgrade ember-changeset even if we don't want to and we haven't fixed our changeset helper code to cater for ember-changeset changes in https://github.com/poteto/ember-changeset/tree/v2.2.0

Maybe it's just on our side and we haven't found the right combination of packages to make it work though. cc @sarahs07 @aneeshcentrica

**Comment by Leooo** [comment]
Still, if there is nothing problematic about removing the `^` in https://github.com/poteto/ember-changeset-validations/blob/master/package.json#L28, I would do it for the future.

**Comment by snewcomer** [comment]
I'll look into some of the commits and see what broke the tests here 👍

**Comment by snewcomer** [comment]
Lmk if `2.2.1` fixes your issues!
