### ISSUE TITLE
Not able to get validations to work with Octane

### ISSUE THREAD

**Issue by reggaemahn** [poteto/ember-changeset-validations#214]
Hey all, new to this and looking for some help. 

I've added this library to a new Ember 3.15 (Octane) app and following the examples in the README but having a hard time getting it to validate. There are no (code related) errors in the console but `changeset.isValid` always returns `true`. 

    {{! application/controller.js}}
    import {action} from "@ember/object";
    import MyValidationClass from '../Validations/myValidations';
    
    export default class MyController extends Controller {
      MyValidationClass;
    
      @action
      submit(changeset) { 
        changeset.save()
      }
    }

--

    {{! application/template.hbs}}
    <MyComponent
      @changeset={{changeset this.model this.MyValidationClass}}
      @onSubmit={{this.submit}}
    />

--

    {{! application/components/mycomponent.hbs}}

    <BsForm @formLayout="horizontal" {{on 'submit' (fn this.submit @changeset)}} @model={{@changeset}} as |form|>
      <form.element
        @controlType="text"
        @label="Title"
        @placeholder="Title"
        @property="title"
        @required={{true}}
      />
    </BsForm>

--

    {{! application/components/mycomponent.js}}
    export default class MyComponent extends Component {
        async submit(changeset) {
          await changeset.validate();
             
          if(changeset.isValid) // returns true even when the validation should fail
            this.args.onSubmit(changeset);
        }
    }

--

    {{! application/Validations/myValidations.js}}
    import {
      validateLength,
      validatePresence
    } from 'ember-changeset-validations/validators';
    
    export default {
      title: [
        validatePresence(true),
        validateLength({ min: 44 })
      ]
    };

**Comment by adambedford** [comment]
I think I'm also running into the same / a similar issue

**Comment by snewcomer** [comment]
Do you have a reproduction I can play with?  I tried with the code you pasted above.  The only thing I noticed is the component `save` is called twice...

**Comment by reggaemahn** [comment]
> Do you have a reproduction I can play with? I tried with the code you pasted above. The only thing I noticed is the component `save` is called twice...

No, sorry. Is there somewhere I can setup an emberjs app with addons?

**Comment by snewcomer** [comment]
@reggaemahn Yep, just `ember new validation-test` with the code you pasted above + a simplified version of the actual form + `ember-changeset-validations` installed.  I went down that route but wasn't able to reproduce so I think I need your help in showing me exactly how the submit action is called with the changeset.  Then I can debug and figure it out pretty quickly!

**Comment by reggaemahn** [comment]
I've reproduced the issue with in [this repo](https://github.com/reggaemahn/ember-changeset-validations-issue_214-)

**Comment by snewcomer** [comment]
@reggaemahn Woop woop!  So your `MyValidationsClass` wasn't being assigned as a class field to the instance.  So it is undefined.  Basically you can't use the shorthand syntax for class fields...

```js
export default class MyController extends Controller {
  MyValidationClass = MyValidationsClass;
```

Lmk if I missed anything else and reopen this issue!  (side note - will ensure `isValid` returns `false` and not `undefined` as I saw in your reproduction)

**Comment by reggaemahn** [comment]
Sweet! That worked. Thanks for helping resolve this.
