### ISSUE TITLE
Support for sequential validations

### ISSUE THREAD

**Issue by sinankeskin** [poteto/ember-changeset-validations#220]
I wrote a validator for uniqueness of the email address. This validator asking the api if the email exists in the database.

Here is my validation:
```js
export default {
  email: [
    validatePresence(true),
    validateFormat({ type: 'email' }),
    validateUniqueness({ message: 'Mail adresi bulunuyor' })
  ]
};
```

No matter what, if I change the email all validations running again. This is expensive for me because it creates a new uniqueness check request everytime.

How about an option for sequential validations?

For my example; Look for the presence and if true check the format and if also true check for the uniqueness.

That way, this change will create request only  if previous validation has returned true.

Thank you.

**Comment by basz** [comment]
solved by a wrapping function which iterates over provided validators until an error occurs.

```
import priorityValidator from 'validators/priority';

export default {
  email: priorityValidator([
    validatePresence(true),
    validateFormat({ type: 'email' }),
    validateUniqueness({ message: 'Mail adresi bulunuyor' })
  ])
};
```
```
// validators/priority.js
export default function priorityValidator(validators) {
  return (key, value, _oldValue, changes, content) => {
    let result;

    let index = 0;
    do {
      let validator = validators[index++];

      result = validator(key, value, _oldValue, changes, content);
    } while (true === result && index < validators.length);

    return result;
  };
}
```

**Comment by sinankeskin** [comment]
Hi @basz

Nice solution. Thank you.

**Comment by snewcomer** [comment]
I like this solution.  I'll look at adding some documentation!

**Comment by BryanCrotaz** [comment]
> I wrote a validator for uniqueness of the email address. This validator asking the api if the email exists in the database.

How are you authenticating your request without access to ember services?

**Comment by sinankeskin** [comment]
> > I wrote a validator for uniqueness of the email address. This validator asking the api if the email exists in the database.
> 
> How are you authenticating your request without access to ember services?

It's on server side. There is no authentication process. All anonymous. For example; user registration.
