### ISSUE TITLE
3.0.0 fails with errors due to missing isPromise function

### ISSUE THREAD

**Issue by rhyselsmore** [poteto/ember-changeset-validations#223]
## Version

3.0.0

## Steps to reproduce

3.0.0 imports `isPromise` from `ember-changeset/utils/is-promise`. 

However, in `ember-changeset@3.0.0`, `isPromise` has been moved, and is now located in `validated-changeset`.

This results in build errors because `isPromise` cannot be imported.

## Next Steps

Would you like me to make a PR for `ember-changeset-validations` that references `isPromise` from `validated-changeset`?

**Comment by snewcomer** [comment]
@rhyselsmore that would be great!  Sorry about that.
