### ISSUE TITLE
Value of `error.${property}.validation` is different from ember-changeset

### ISSUE THREAD

**Issue by jelhan** [poteto/ember-changeset-validations#228]
Accordingly to ember-changeset docs `error.${property}.validation` should be a string: https://github.com/poteto/ember-changeset#error

This is also what is being covered by tests in ember-changeset: https://github.com/poteto/ember-changeset/blob/54131fe84e02de7b4c01344c0d7dd8dbe494641a/tests/unit/changeset-test.js#L82-L93

But if using ember-changeset-validations the value of `error.${property}.validation` is an array of strings. If I didn't missed something this is not documented. But it's covered by tests, e.g. here: https://github.com/poteto/ember-changeset-validations/blob/a4a87d02eb3221b2e14dfb11f13966ef14d8abcf/tests/unit/helpers/changeset-test.js#L41

**Comment by snewcomer** [comment]
@jelhan What is expected by bootstrap-validations?  An array right?  We have a typespec that it can be a string or string[], so I think there might be a bug in https://github.com/validated-changeset/validated-changeset/.

What do you think?

**Comment by snewcomer** [comment]
@jelhan I think it makes sense to return the validation as a string if 1 and an array if multiple (this is what validated-changeset does).  What do you think?

**Comment by ohcibi** [comment]
@snewcomer the problem here is that the computed property for `error.${property}.validation` is not updated for some reason.

**Comment by ohcibi** [comment]
Also here #143 seems related

**Comment by jelhan** [comment]
> @jelhan I think it makes sense to return the validation as a string if 1 and an array if multiple (this is what validated-changeset does). What do you think?

Actually I don't care that much to be honest. It adds a little bit of additional complexity if it could be both. But that might be valuable. And I don't think we should have another major release just for changing that one.

But the readme of ember-changeset should be updated to mention both options. Cause that was what actually confused me.

**Comment by snewcomer** [comment]
https://github.com/validated-changeset/validated-changeset/pull/32/files#r415328613
