### ISSUE TITLE
Normalize validation results for lookupValidator function?

### ISSUE THREAD

**Issue by jakebixbyavalara** [poteto/ember-changeset-validations#235]
While using `lookupValidator`, I noticed that the validation results from keys with multiple validations return as a single boolean value, while the results for a single validation return the single boolean result wrapped in an array.

Given the following validationMap:
```
{
  firstName: [
    validatePresence(true),
    validateLength({ min: 4 })
  ],
  lastName: validatePresence(true),
}
```

A valid result for `firstName` would be the boolean value `true`, with no array wrapper.
But a valid result for `lastName` would be `[true]`, the boolean wrapped in an array.

The invalid result for both keys appears to be consistent.

The reason for this is that results from `handleMultipleValidations` returns a single boolean value:
https://github.com/poteto/ember-changeset-validations/blob/master/addon/index.js#L16

But from a single validation result, it wraps it in an array:
https://github.com/poteto/ember-changeset-validations/blob/master/addon/index.js#L21

I don't know if this really matters, but in writing something to transition our current model validation setup to `ember-changeset-validations`, I noticed the inconsistency in the returned results which threw me. If it would be desired to normalize the results, I'd be happy to make a pull request.

Thanks!

**Comment by snewcomer** [comment]
👋 I agree we should be consistent.  Seems like a single result is the way to go.  A PR would be great!

**Comment by jakebixbyavalara** [comment]
So to clarify, it seems that the [wrapInArray](https://github.com/poteto/ember-changeset-validations/blob/master/addon/index.js#L21) has some purpose (not totally sure what yet), so I hesitate to make the results from line 21 to not be an array. Do we want to wrap the result of `handleMultipleValidations` in an array instead?

**Comment by snewcomer** [comment]
Looks like we have it in two places.  However no low level tests for the validator itself :(.  This alone would be huge. 

https://github.com/validated-changeset/validated-changeset/blob/b690e25ecfbcbab74378cce6862c1658d532689b/src/utils/validator-lookup.ts

However, back to your question...This looks to be the original implementation.

https://github.com/poteto/ember-changeset-validations/commit/43f2621c43c8200378604f70900d9db37f83d259#diff-7562eb8eba3c3d86a671045f8c70107e

And I'm now curious how this is supposed to work when it is expecting a boolean (should be typed!).

https://github.com/validated-changeset/validated-changeset/blob/master/src/index.ts#L727

So overall if we started a test and confirm this is true, then we might see where we went wrong and understand if the `wrapInArray` is unncessary.

What are your thoughts?

**Comment by jakebixbyavalara** [comment]
I have very little TypeScript experience, so I'm going to need to do some parsing and sit with it for a bit to fully understand what's going on. I am curious if it would be beneficial (or possible) to import the `lookupValidator` from validated-changeset instead of duplicating it. From the array standpoint, it would be an Ember array anyhow with extended prototypes (though if someone has that turned off, maybe that's an issue?).

Anyhow, I'm thinking that maybe fix it in validated-changeset and then start importing (and re-exporting) the functions from validated-changeset so there's less chance of drift between the two repos?

**Comment by snewcomer** [comment]
That seems like a good idea.  Start from there with unit tests and then jump up here to replace this import.  

Note there is one big difference - `wrap` in e-c-v turns it into an EmberArray.  However, generally back in the day (for good reason) ubiquitous use of ember-isms was the default.  Today we should default to use plain JS and reach for these layers of indirection if necessary.  In this, case I don't think this (EmberArray) level of indirection is necessary.

We will also need to maintain the import in e-c-v for current users importing it (like e-c).

**Comment by snewcomer** [comment]
@jakebixbyavalara Ok did some investigation.  First, it looks like it is a possibility that the specific validator function returns an array as its type [here](https://github.com/validated-changeset/validated-changeset/blob/master/src/utils/wrap.ts#L9).  Second, we have various [tests](https://github.com/poteto/ember-changeset/blob/v2.2.5/addon/helpers/changeset.ts) of the `lookupValidator` implicitly for tests that involve the changeset helper.

From a pure functionality point of view, we handle the validation accordingly (whether an array or primitive).  So I believe everything works as expected.

https://github.com/validated-changeset/validated-changeset/blob/master/src/index.ts#L688

I am going to suggest we refactor to always return a primitive from `lookupValidator`.  We never iterate through the list and if we do, we check the first item in the array.  Does that sound good to you?
