### ISSUE TITLE
Validations not updating correctly at on focus out

### ISSUE THREAD

**Issue by visoft** [poteto/ember-changeset-validations#236]
I'm having a problem with a very simple form not validating correctly. This is using 3.2.1 and I have replicated it in a Twiddle:

https://ember-twiddle.com/0d0a0f211c818a5300b4deaac7e159d6?openFiles=templates.application%5C.hbs%2C

If you click on the name field and then click elsewhere, you'll see name is marked as valid (green checkmark) even though it's required by the validator. This appears to be an issue with the validations, but if you click submit, the validate function is called and all is well.

I previously reported this here: https://github.com/kaliber5/ember-bootstrap-changeset-validations/issues/22, but with the added code, you can see it's valid until the submit button is pressed.

**Comment by snewcomer** [comment]
You might be right! I think a first step would be to add a test for this case in this repo.  Is that something you would like to PR or would you like me to?

https://github.com/poteto/ember-changeset-validations/blob/master/addon/validators/presence.js

**Comment by visoft** [comment]
@snewcomer I can try to get A PR in tonight

**Comment by snewcomer** [comment]
See comment in PR!  Thanks for bringing it to our attention!
