### ISSUE TITLE
Adding the ignoreBlank flag when validating length

### ISSUE THREAD

**Issue by anandlall112** [poteto/ember-changeset-validations#265]
validateLength() seems to include white-spaces when validating the string length. I think it would make a great addition to also allow the ignoreBlank flag when validating length to ignore counting white-spaces, similar to validatePresence()

```
    validatePresence({
      presence: true,
      ignoreBlank: true
    }),
    validateLength({
      is: 4,
      allowBlank: false
    })
```

**Comment by snewcomer** [comment]
👋 It might be best for this case to write your own validator for now.  This issue would ideally be handled in `ember-validators` (we just consume their helpers).  If you so desire, an issue over there might be worthwhile!  I do agree that a string should be trimmed before validation.

https://github.com/poteto/ember-changeset-validations#writing-your-own-validators
https://github.com/offirgolan/ember-validators/blob/master/addon/length.js
